# Generated by Django 4.1.7 on 2023-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userreport_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='username',
            field=models.CharField(help_text='Emri', max_length=100, unique=True),
        ),
    ]
